### PR TITLE
Cookies: define a specific cookie store

### PR DESCRIPTION
**Pull request by andreastt**
Defines precisely which cookie store cookies are fetched from, and also
addresses the issue that we did not mandate to include HTTP-only cookies.

Thanks to Jim Evans for input.

[Review on Reviewable](https://reviewable.io/reviews/w3c/webdriver/214)

### CODE REVIEW

**Comment by andreastt** [comment]
@AutomatedTester Removed the storage mutex provision.

**Comment by AutomatedTester** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[webdriver-spec.html, line 4068 \[r2\]](https://reviewable.io:443/reviews/w3c/webdriver/214#-Jxj9LeLWek7vxlWSmZs)** ([raw file](https://github.com/w3c/webdriver/blob/1b8ebfd2316e46ab1d780d0445fff858e9876872/webdriver-spec.html#L4068)):</sup>
this line is not needed as you have said that it is associated to the document address below.

---

<sup>**[webdriver-spec.html, line 4074 \[r2\]](https://reviewable.io:443/reviews/w3c/webdriver/214#-Jxj9mtaOh1EOr4xEIV7)** ([raw file](https://github.com/w3c/webdriver/blob/1b8ebfd2316e46ab1d780d0445fff858e9876872/webdriver-spec.html#L4074)):</sup>
what is an `HTTP API`

---

<sup>**[webdriver-spec.html, line 4161 \[r2\]](https://reviewable.io:443/reviews/w3c/webdriver/214#-JxjA49iH7Iv9m3Wzhgf)** ([raw file](https://github.com/w3c/webdriver/blob/1b8ebfd2316e46ab1d780d0445fff858e9876872/webdriver-spec.html#L4161)):</sup>
s/switching/matching/ so that it is more in line with the rest of the specification

---

<sup>**[webdriver-spec.html, line 4269 \[r2\]](https://reviewable.io:443/reviews/w3c/webdriver/214#-JxjAMYStr1wzztmRmcQ)** ([raw file](https://github.com/w3c/webdriver/blob/1b8ebfd2316e46ab1d780d0445fff858e9876872/webdriver-spec.html#L4269)):</sup>
I don't think this issue is valid since no UA implements `storage mutex` and the storage model in the RFC is an exercise for the reader

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/webdriver/214)

**Comment by andreastt** [comment]
<sup>**[webdriver-spec.html, line 4074 \[r2\]](https://reviewable.io:443/reviews/w3c/webdriver/214#-Jxj9mtaOh1EOr4xEIV7)** ([raw file](https://github.com/w3c/webdriver/blob/1b8ebfd2316e46ab1d780d0445fff858e9876872/webdriver-spec.html#L4074)):</sup>
RFC 6265 makes the distinction between a ‘non-HTTP’ and ‘HTTP’ API.  Basically the difference is that when retrieving cookies via the HTTP API, cookie’s which `http-only-flag` is true are included.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/webdriver/214)

**Comment by andreastt** [comment]
<sup>**[webdriver-spec.html, line 4068 \[r2\]](https://reviewable.io:443/reviews/w3c/webdriver/214#-Jxj9LeLWek7vxlWSmZs)** ([raw file](https://github.com/w3c/webdriver/blob/1b8ebfd2316e46ab1d780d0445fff858e9876872/webdriver-spec.html#L4068)):</sup>
The line below should probably say “for the current browsing context’s document”

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/webdriver/214)

**Comment by AutomatedTester** [comment]
landed in 71bde4f

**Pull request closed without merging**
