### PR TITLE
Correct dispatch of key actions.

### PR DESCRIPTION
**Pull request by mjzffr**
PR includes some inline comments that ask for clarification -- these will be removed.

@jgraham @AutomatedTester r?

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/webdriver/443)

### CODE REVIEW

**Comment by mjzffr** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[webdriver-spec.html, line 6621 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJb5bKtGq4woB_sddc:-KXJb5bKtGq4woB_sddd:b-wu0k9m) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L6621)):*
> ```HTML
> 
>             <li><p>If <var>action object</var> has <code>subtype</code>
>                 property set to <code>"pause"</code> or
> ```

The check of the "type" property doesn't seem necessary when subtype is "pause".

---

*[webdriver-spec.html, line 7052 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJcVIr_joHDqIXJpeu:-KXJcVIs36dLRizQ5liz:bmqawyw) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7052)):*
> ```HTML
>             be true.</li>
> 
>         <li><p>If <var>key</var> is <code>"Control"</code>,
> ```

Clarification: if we have |keyDown Control| followed immediately by |keyDown a|, then according to this part of the spec the keyboard event for |keyDown a| will have `ctrlKey` set to `true` because nothing reverts the device state's `ctrl` property until we see a |keyUp Control| action. Is this the intended behaviour?

---

*[webdriver-spec.html, line 7070 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJbsKQIXE1z-L_jrbm:-KXJbsKRJEDv07ZubLoD:b7r0itk) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7070)):*
> ```HTML
>         implementation-specific action dispatch steps</a> equivalent
>         to pressing a key on the keyboard in accordance with the
>         requirements of [[!UI-EVENTS]], and producing at least the
> ```

Re "at least the following events": I noticed that in Firefox, for example, the keypress event is only sent if the key is not a modifier key, which seems to contradict what the spec says here. Should the "at least" be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/443)*

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[webdriver-spec.html, line 6621 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJb5bKtGq4woB_sddc:-KXKkf284uoq7ZUVC3s7:b-lthjne) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L6621)):*
<details><summary><i>Previously, mjzffr (Maja Frydrychowicz) wrote…</i></summary>
> The check of the "type" property doesn't seem necessary when subtype is "pause".
</details>
Right, I was just being explicit about the full (type, subtype) pair. 

---

*[webdriver-spec.html, line 7052 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJcVIr_joHDqIXJpeu:-KXKkN8o-untPNE5yg2R:bb77ufg) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7052)):*
<details><summary><i>Previously, mjzffr (Maja Frydrychowicz) wrote…</i></summary>
> Clarification: if we have |keyDown Control| followed immediately by |keyDown a|, then according to this part of the spec the keyboard event for |keyDown a| will have `ctrlKey` set to `true` because nothing reverts the device state's `ctrl` property until we see a |keyUp Control| action. Is this the intended behaviour?
</details>
Yes.

---

*[webdriver-spec.html, line 7070 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJbsKQIXE1z-L_jrbm:-KXKkRCGTeVHiiSODWHo:b-jm2ci7) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7070)):*
<details><summary><i>Previously, mjzffr (Maja Frydrychowicz) wrote…</i></summary>
> Re "at least the following events": I noticed that in Firefox, for example, the keypress event is only sent if the key is not a modifier key, which seems to contradict what the spec says here. Should the "at least" be removed?
</details>
Oh, interesting point. Perhaps this should use language more like that for pointer actions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/443)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[webdriver-spec.html, line 7015 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXRGhRGE1bYmBQ-sIH2:-KXRGhRGE1bYmBQ-sIH3:b-6kil9i) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7015)):*
> ```HTML
>         </table>
> 
>       
> ```

Right, but the idea was to have a consistent internal interface rather than adding special cases. I guess I don't really mind what we do.

---

*[webdriver-spec.html, line 7179 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXRHWCdctdo5bqXu_p9:-KXRHWCdctdo5bqXu_pA:bx418vr) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7179)):*
> ```HTML
>             be false.</li>
> 
>         <li><p>Remove <var>key</var> from the set corresponding
> ```

I don't think we should be removing the key here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/443)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[webdriver-spec.html, line 7179 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXRHWCdctdo5bqXu_p9:-KXRbNUpilNg5_C6U-_h:b-wi8m8y) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7179)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't think we should be removing the key here.
</details>
Oh, I was mistaken.

---

*[webdriver-spec.html, line 7184 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXRbDHg12GytMZSWkvg:-KXRbDHhEy2NvUaqFDXa:balhv1z) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7184)):*
> ```HTML
>         <li><p><a data-lt="perform-actions">Perform
>             implementation-specific action dispatch steps</a>
>             equivalent to pressing a key on the keyboard in accordance
> ```

This should say "releasing".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/443)*

**Comment by mjzffr** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[webdriver-spec.html, line 6621 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJb5bKtGq4woB_sddc:-KXRmoHzZ77fsO3h44tG:b-tpyuz3) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L6621)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Right, I was just being explicit about the full (type, subtype) pair. 
</details>
I'll keep the change since "pause" occurs with all types, not just "none".

---

*[webdriver-spec.html, line 7070 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXJbsKQIXE1z-L_jrbm:-KXRn6G-i-p-T3ONGcn4:bf9sha5) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7070)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Oh, interesting point. Perhaps this should use language more like that for pointer actions.
</details>
I've reworded this to say "at least keyDown".

---

*[webdriver-spec.html, line 7184 at r1](https://reviewable.io:443/reviews/w3c/webdriver/443#-KXRbDHg12GytMZSWkvg:-KXRnIDhrSsQYg9RdOXd:b-896fix) ([raw file](https://github.com/w3c/webdriver/blob/4abe02b8661cdbe209be7a9e3096dd50da5c81ff/webdriver-spec.html#L7184)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This should say "releasing".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/443)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/443)*

**Comment by jgraham** [comment]
@AutomatedTester r+, feel free to merge

**Pull request merged**
