### PR TITLE
Define Unexpected Alert Behaviour capability. Fixes #402

### LINKED ISSUE #402: Describe how to set the "user prompt handler"
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29778

juangj:

> "A user prompt handler is an enumerated attribute defining what action the remote end must take when a user prompt is encountered. The following table lists the keywords and states for the attribute:"
> 
> How is the user prompt handler defined? Via a capability? The name of the capability should be defined.

### PR DESCRIPTION
**Pull request by AutomatedTester**
This is used to set the value of the user prompt handler
for when encountering a modal dialog.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/webdriver/606)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Open questions: 
* Selenium simply has this a boolean, do we change the spec to match?
* Do we allow boolean values and `true` === `accept` and `false` === `dismiss` with `null` meaning there isnt one defined for the session?

**Comment by andreastt** [comment]
Is it really called `unexpectedAlertBehaviour` in any drivers? It would be nice if you could configure the user modal handler by string "accept" (accept state), "dismiss" (dismiss), or null (default boolean attribute missing state) instead of magic variables such as true/false.

**Comment by shs96c** [comment]
A string as the value would be nice.

**Comment by shs96c** [comment]
@andreastt It really is called "[unexpectedAlertBehaviour](https://github.com/SeleniumHQ/selenium/blob/selenium-3.0.1/java/client/src/org/openqa/selenium/remote/CapabilityType.java#L42)"

**Comment by AutomatedTester** [comment]
This is ready to go then if we are going to leave it with the current values

**Comment by shs96c** [comment]
Merging this in, but we should consider using the en-US spelling.

**Pull request merged**
