### PR TITLE
Rename ImplementationReport.md to implementation-report.md

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/w3c/webdriver/issues/1508.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Do we need this file at all with wpt.fyi reporting these things?

**Comment by foolip** [comment]
The "Vendor status documents" links are kind of useful, but maybe put those in the README instead?

**Comment by AutomatedTester** [comment]
yea, let's move it to the README

**Comment by foolip** [comment]
Closing in favor of https://github.com/w3c/webdriver/pull/1517

**Pull request closed without merging**
