### PR TITLE
Fix browsing context checks for Switch To Parent Frame when already the top-level browsing context

### PR DESCRIPTION
**Pull request by whimboo**
Fixes issue #1544.

@jgraham or someone else, can you please review? Thanks

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1556.html" title="Last updated on Oct 16, 2020, 12:26 PM UTC (da1275a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1556/99f7ced...da1275a.html" title="Last updated on Oct 16, 2020, 12:26 PM UTC (da1275a)">Diff</a>

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Are there tests for this?

**Comment by AutomatedTester** [comment]
Are there tests for this?

**Comment by whimboo** [comment]
If those changes make sense I will immediately file a bug, and add new tests, or update existing ones.

**Comment by AutomatedTester** [comment]
Makes sense to me

**Comment by whimboo** [comment]
There is https://bugzilla.mozilla.org/show_bug.cgi?id=1671622 now.

**Comment by whimboo** [comment]
Patch for the updated tests has been uploaded and is under review now.

**Review by AutomatedTester — APPROVED** [review]

**Pull request merged**
