### PR TITLE
Update HTML attributes to use quotes

### PR DESCRIPTION
**Pull request by InstyleVII**
Added quotes to all HTML attributes to improve editor tooling.

***
<a href="https://pr-preview.s3.amazonaws.com/InstyleVII/webdriver/pull/1186.html" title="Last updated on Jan 8, 2018, 8:48 PM GMT (39de95d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1186/e9d00b7...InstyleVII:39de95d.html" title="Last updated on Jan 8, 2018, 8:48 PM GMT (39de95d)">Diff</a>

### CODE REVIEW

**Comment by InstyleVII** [comment]
This is an updated version of my previous PR with just the addition of quotes to all HTML attributes as well as one minor fix to an incorrect class name.

**Comment by andreastt** [comment]
I don’t see the value of this PR at all. This is not incorrect usage of attributes.

**Comment by InstyleVII** [comment]
Two mains reasons:
Editor tooling - Some editors won't read links as links allowing you to nav to them from the editor if they aren't in quotes
Consistency - We had some attributes using quotes and others not using quotes, now the document is consistent

**Comment by andreastt** [comment]
The document is pretty much consistent in not using quotes where it is unnecessary already, so I wouldn’t go as far as calling that an inconsistency. I would also consider it a bug that your editor doesn’t recognise valid HTML attributes.

Now I’m not going to block a patch that adds quotes everywhere, but I would like to reiterate that they are completely pointless.

**Comment by InstyleVII** [comment]
@shs96c mind assigning a reviewer?

**Comment by InstyleVII** [comment]
Going to close as consensus is this isn't needed.

**Pull request closed without merging**
