### PR TITLE
Neither one of "visibility", "interactibility" implies the other.

### PR DESCRIPTION
**Pull request by sevaseva**
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28407 is related (but I think it makes a falsy statement where it uses logical 'weaker').

### CODE REVIEW

**Comment by andreastt** [comment]
Can probably be replaced by #25 or the other way around.

**Comment by sevaseva** [comment]
I'll cherry-pick that commit to this PR later today

**Comment by sevaseva** [comment]
Actually.. why not consider/submit deletion of these two sentences separately. There are different reasons for deleting them. The two changes may meet separate discussions, too...

**Comment by andreastt** [comment]
I'm sure that's OK.

**Comment by AutomatedTester** [comment]
landed in 3eb3dd3

**Pull request closed without merging**
