### PR TITLE
Rename Get command to Go

### PR DESCRIPTION
**Pull request by andreastt**

### CODE REVIEW

**Comment by AutomatedTester** [comment]
what is the reason behind this?

**Comment by andreastt** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29520

**Comment by AutomatedTester** [comment]
landed in 891bfd1, d46720d

**Comment by shs96c** [comment]
We should roll this back. The command is named after the HTTP verb "GET", and is widespread use throughout existing webdriver implementations.

**Comment by andreastt** [comment]
@burg’s argument is that it’s confusing exactly for that reason, because it’s actually a POST.

**Comment by shs96c** [comment]
But it results in the browser executing a GET request, as opposed to a POST. For implementations of webdriver that don't use HTTP as the transport mechanism the ambiguity doesn't exist.

Admittedly, the spec is defining an HTTP protocol, but that's to ensure interop. I can imagine later levels of the spec using (for example) a standardised debugging protocol.

**Comment by uchuugaka** [comment]
Personally, I always thought it should be named request.
Because it is a request.

**Comment by andreastt** [comment]
Personally I feel perhaps the most descriptive name would be _Navigate_, as this is the [algorithm we’re calling down to](https://html.spec.whatwg.org/#navigate) in HTML. But as I said earlier on the bug, I really don’t have any strong opinions on the matter.

**Comment by andreastt** [comment]
Also this change has already landed, so I’m closing the PR. We can consider reverting the change.

**Pull request closed without merging**
