### PR TITLE
Adding the step to handle user prompts for screenshots

### PR DESCRIPTION
**Pull request by thejohnjansen**
At TPAC we agreed to add the steps to handle user prompts where necessary throughout the spec. I am working on elementScreenShot and takeElementScreenShot commands, so it seems like a good time to add it there.

***
<a href="https://pr-preview.s3.amazonaws.com/thejohnjansen/webdriver/pull/1405.html" title="Last updated on Mar 22, 2019, 6:07 PM UTC (4ce49f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1405/ab946e6...thejohnjansen:4ce49f4.html" title="Last updated on Mar 22, 2019, 6:07 PM UTC (4ce49f4)">Diff</a>

### CODE REVIEW

**Comment by thejohnjansen** [comment]
I subsequently linked my Github account with my W3C Account, so that check should now pass. I'm not sure how to re-run that check, though, to make it green.

**Comment by sideshowbarker** [comment]
> I subsequently linked my Github account with my W3C Account, so that check should now pass. I'm not sure how to re-run that check, though, to make it green.

I’ve gone ahead and done that, so it’s all green now

**Comment by thejohnjansen** [comment]
> > I subsequently linked my Github account with my W3C Account, so that check should now pass. I'm not sure how to re-run that check, though, to make it green.
> 
> I’ve gone ahead and done that, so it’s all green now

Thanks so much!

**Comment by thejohnjansen** [comment]
whoops. I didn't mean to "close" this.

**Comment by thejohnjansen** [comment]
Incidentally, here are the fixed tests that I asked Stanley to work on. This all now means that Firefox fails those tests. 
https://github.com/stanleyhon/web-platform-tests/commit/2418addf2c4921dfe7450e371197360a77f8b37c

We also logged an orthogonal new bug to Chromium. https://bugs.chromium.org/p/chromedriver/issues/detail?id=2820&q=unhandledpromptbehavior&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by andreastt** [comment]
@whimboo did some work recently in the area of handling user prompts, and I believe even added some more of these checks to the spec. Perhaps he could take a look.

**Comment by thejohnjansen** [comment]
> This isn’t a review as such, so feel free to dismiss it at a later point when addressed, but we can’t landt this without new tests.

We do already have tests in WPT for this, I linked them in my comment above. Do you want to block landing this until more tests are written, or are you ok with the current coverage?

**Comment by whimboo** [comment]
The tests for webdriver in wpt are written to check that no user prompt is handled. If you propose the above change the tests for both screenshot commands have to be updated.

**Comment by AutomatedTester** [comment]
@thejohnjansen could you check the tests and comment whether they are doing what your change is suggesting?

**Comment by stanleyhon** [comment]
I checked that the web-platform-tests in it's current state test that take screenshot and take element screenshot completely ignore unhandledpromptbehavior.

I made a PR over here https://github.com/web-platform-tests/wpt/pull/17563 to update the tests to check unhandledPromptBehaviors are respected however this test does fail in Firefox.

Based on John's initial post it sounds like this is the direction we want to go.

If these two PRs go in at the same time, the tests and spec will be in agreement.

**Comment by andreastt** [comment]
This behavioural spec change was landed without tests. From what I can tell https://github.com/web-platform-tests/wpt/pull/17563 still requires fixups.

@stanleyhon, will you follow up on this? Otherwise I am inclined to request this spec change to be reverted, @AutomatedTester.

**Comment by stanleyhon** [comment]
@andreastt i will work on landing https://github.com/web-platform-tests/wpt/pull/17563 on my Monday as a high priority.

**Comment by andreastt** [comment]
Perfect! 👍🏻

**Comment by AutomatedTester** [comment]
> @stanleyhon, will you follow up on this? Otherwise I am inclined to request this spec change to be reverted, @AutomatedTester.

As discussed at TPAC there was going be a followup from Microsoft

**Comment by whimboo** [comment]
FYI the tests on https://github.com/web-platform-tests/wpt/pull/17563 just got merged.

**Pull request merged**
