### PR TITLE
Add references to JSON Objects and Lists

### PR DESCRIPTION
**Pull request by andreastt**
No functional changes except a few style corrections.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/webdriver/435)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[webdriver-spec.html, line 1656 at r1](https://reviewable.io:443/reviews/w3c/webdriver/435#-KUwxjNhxQpPgzmI1jN_:-KUwxjNiPA78sgNIBd1z:b-832u29) ([raw file](https://github.com/w3c/webdriver/blob/8893b72a7992483031d9b63713027c232147a4d3/webdriver-spec.html#L1656)):*
> ```HTML
>  within the primary <a>capabilities</a>.
>  Implementations may define additional proxy configuration options,
>  but they msut not alter the semantics of those listed below.
> ```

s/msut/must/ 

It's the only issue so I will sort it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/435)*

**Comment by AutomatedTester** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/webdriver/435)*

**Comment by AutomatedTester** [comment]
landed in 834bb8b

**Comment by andreastt** [comment]
Thanks.

**Pull request closed without merging**
