### PR TITLE
Bring error handling section to the left

### PR DESCRIPTION
**Pull request by andreastt**
Apart from adding a few references, there are no functional changes.

[Review on Reviewable](https://reviewable.io/reviews/w3c/webdriver/150)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[webdriver-spec.html, line 792 \[r1\]](https://reviewable.io:443/reviews/w3c/webdriver/150#-JvaUuo4-vhzwGyEWX0l)** ([raw file](https://github.com/w3c/webdriver/blob/38ebda1d53f3d78548afbd448e2d0a537e58e7f2/webdriver-spec.html#L792)):</sup>
missing `</dfn>`. Most of the patch has this issue 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/webdriver/150)

**Comment by andreastt** [comment]
<sup>**[webdriver-spec.html, line 792 \[r1\]](https://reviewable.io:443/reviews/w3c/webdriver/150#-JvaUuo4-vhzwGyEWX0l)** ([raw file](https://github.com/w3c/webdriver/blob/38ebda1d53f3d78548afbd448e2d0a537e58e7f2/webdriver-spec.html#L792)):</sup>
This is actually not so much an issue because `<dfn>` is self-closing like  `<p>`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/webdriver/150)

**Comment by andreastt** [comment]
<sup>**[webdriver-spec.html, line 792 \[r1\]](https://reviewable.io:443/reviews/w3c/webdriver/150#-JvaUuo4-vhzwGyEWX0l)** ([raw file](https://github.com/w3c/webdriver/blob/38ebda1d53f3d78548afbd448e2d0a537e58e7f2/webdriver-spec.html#L792)):</sup>
I didn't mean to resolve this.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/webdriver/150)

**Comment by AutomatedTester** [comment]
According to the HTML spec neither tag is omissible. https://html.spec.whatwg.org/#the-dfn-element



—

**Comment by andreastt** [comment]
@AutomatedTester You’re right.  `<dfn>` isn’t an [implied end tag](https://html.spec.whatwg.org/#closing-elements-that-have-implied-end-tags).

**Comment by AutomatedTester** [comment]
landed in 9196bc3

**Pull request closed without merging**
