### PR TITLE
Ensure all resources are published with Echnida

### PR DESCRIPTION
**Pull request by andreastt**

### CODE REVIEW

**Comment by AutomatedTester** [comment]
@sideshowbarker does Echnida understand directories?

**Comment by sideshowbarker** [comment]
> @sideshowbarker does Echnida understand directories?

It may not yet; I'm not sure. @tripu and @deniak would be able to tell us.

**Comment by tripu** [comment]
@AutomatedTester, @sideshowbarker: it does; Echidna will grab any files that are under any subdirectory that is publicly accessible, as long as they're listed in the manifest that is passed to it.

@andreastt could move images back to their original directory, prepend `svgs/` to those lines in the manifest, and restore the paths in the references to those images.

\+ info: [compound documents](https://github.com/w3c/echidna/wiki/How-to-use-Echidna#request-a-publication) &mdash; [a simple example of a manifest with one HTML and one image in a subdirectory](https://github.com/w3c/echidna/wiki/How-to-use-Echidna-with-ReSpec-and-GitHub#actually-publishing) &mdash; [the manifest used in real life](https://github.com/w3c/manifest/blob/gh-pages/ECHIDNA).

(`s/Echnida/Echidna/g` :¬)

**Comment by andreastt** [comment]
The reason for moving the images to the root directory was more that we already have image files living there.

**Comment by tripu** [comment]
Sure, @andreastt.
Anyway, if you people ever need subdirectories, now you know you can :¬)

**Comment by andreastt** [comment]
@tripu How do I subscribe to public-tr-notifications@w3.org?  Emailing public-tr-notifications-request@ with "subscribe" in the topic doesn't seem to work for me.

**Comment by tripu** [comment]
@andreastt: subscriptions to that public list seem to be disabled. I don't know why; I'm looking into it.

In the meantime, please send me a message (`antonio` at `w3`) from the e-mail address you want to get subscribed, and I'll subscribe you manually.

(It is always possible to read the archive for that list at [`lists.w3.org/Archives/Public/public-tr-notifications/latest`](https://lists.w3.org/Archives/Public/public-tr-notifications/latest), if the list is too noisy for you. I know most users of Echidna do just that &mdash; I guess that's why I hadn't noticed until today that subscriptions aren't allowed!)

**Comment by tripu** [comment]
(@andreastt is now subscribed to the list)

**Comment by AutomatedTester** [comment]
We have 1 image file in the root, I think it would be better to move svg to images and move that 1 file in there instead.

**Comment by andreastt** [comment]
WFM!

**Comment by AutomatedTester** [comment]
landed in 88ecbfc

**Comment by deniak** [comment]
@AutomatedTester if you are using subdirs, you'll have to specify each resources explicitly in the manifest, like:
```
graphics/note1actions.svg
graphics/note2actions.svg
...
```
Echidna [failed to publish the last webdriver update](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Aug/0016.html).

**Comment by andreastt** [comment]
@deniak See #212.

**Comment by deniak** [comment]
Great, thanks @andreastt

**Pull request closed without merging**
