### PR TITLE
Make some preliminary changes to define the screenshot section better.

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by andreastt** [comment]
Ship it 👍🏻

**Comment by thejohnjansen** [comment]
fix the misspelling of "and" on line 4528 :-)

**Comment by thejohnjansen** [comment]
Based on our conversation at the face-to-face, I thought we agreed the default would be to capture the viewport, but that browsers could also get the entire document by using getSize() of the body element.

http://www.w3.org/2014/10/30-testing-minutes.html#item10

**Comment by andreastt** [comment]
Yes, we still need to redefine the screenshot commands.

**Comment by andreastt** [comment]
@jgraham Will you rebase this?

**Comment by AutomatedTester** [comment]
landed in 5c3376c

**Pull request closed without merging**
