### PR TITLE
Replace bug-assist.js with issue.js

### PR DESCRIPTION
**Pull request by andreastt**
This allows issues to contain quotes from the document by selecting text.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/webdriver/414)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This doesnt appear to work for me. There is no widget on the page or when anything is selected.
issue_issue

**Comment by andreastt** [comment]
That’s not a very good bug report, but I’m guessing the Firefox you’re using is too old. I’ll see if I can figure out what’s wrong and backport it.

**Comment by AutomatedTester** [comment]
> That’s not a very good bug report, but I’m guessing the Firefox you’re using is too old. I’ll see if I can figure out what’s wrong and backport it.

It doesnt work in Nightly or Aurora or Beta or Release. Since this is supposed to be for all implementors I suggest you make sure it works in all browsers.

**Comment by andreastt** [comment]
I found selection events [aren’t enabled outside of Firefox Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1242718), but fortunately there’s [a polyfill](https://github.com/2is10/selectionchange-polyfill) that sufficiently supports the features needed to make Firefox work. Chrome has on the other hand shipped this for a long time.

This does not explain why it does not work in Nightly for you, however.

**Comment by AutomatedTester** [comment]
landed in 8486206

**Pull request closed without merging**
